// Auto-generated by LibreLane
module mm_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[7:0] input_data,
  input start,
  input read_ram,
  output[8:0] read_data_out,
  output finish
);
endmodule
